#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
# Sunrise Image Manager - Deployment Script
#
# Deploys the full stack:
#   1. SAM build + deploy (Lambda functions + API Gateway + S3 bucket)
#   2. Upload HTML templates to S3 (templates/ prefix)
#   3. Upload frontend static files to S3 (frontend/ prefix)
#
# Prerequisites:
#   - AWS CLI configured with appropriate credentials
#   - AWS SAM CLI installed (pip install aws-sam-cli)
#   - S3 bucket name set in template.yaml or passed as parameter
#
# Usage:
#   ./deploy.sh                              # Deploy with defaults
#   ./deploy.sh --bucket my-bucket-name      # Deploy with custom bucket
# ──────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
STACK_NAME="sunrise-image-manager"
S3_BUCKET="sunrise-image-manager"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --bucket) S3_BUCKET="$2"; shift 2 ;;
        --stack)  STACK_NAME="$2"; shift 2 ;;
        --region) REGION="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

echo "=== Sunrise Image Manager Deployment ==="
echo "Stack:  $STACK_NAME"
echo "Bucket: $S3_BUCKET"
echo "Region: $REGION"
echo ""

# Step 1: SAM build
echo ">> Building Lambda functions..."
cd "$SCRIPT_DIR/lambda_function"
sam build --template template.yaml

# Step 2: SAM deploy
echo ">> Deploying CloudFormation stack..."
sam deploy \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --resolve-s3 \
    --capabilities CAPABILITY_IAM \
    --parameter-overrides "S3BucketName=$S3_BUCKET" \
    --no-confirm-changeset

# Get outputs
API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='ApiURL'].OutputValue" \
    --output text)

WEBSITE_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" \
    --output text)

echo ""
echo ">> API URL: $API_URL"
echo ">> Website URL: $WEBSITE_URL"

# Step 3: Upload HTML templates to S3
echo ""
echo ">> Uploading HTML templates to S3..."
cd "$SCRIPT_DIR"
aws s3 cp Pano-Template.htm "s3://$S3_BUCKET/templates/Pano-Template.htm" --content-type "text/html"
aws s3 cp img-Template.htm "s3://$S3_BUCKET/templates/img-Template.htm" --content-type "text/html"
aws s3 cp Email-Report-Template.htm "s3://$S3_BUCKET/templates/Email-Report-Template.htm" --content-type "text/html"

# Step 4: Upload frontend with API URL injected
echo ""
echo ">> Uploading frontend to S3..."
# Create a config.js that points to the deployed API
cat > "$SCRIPT_DIR/frontend/config.js" << EOF
// Auto-generated by deploy.sh — points frontend to the deployed API
window.SIM_CONFIG = {
    apiBase: '${API_URL}'
};
EOF

aws s3 sync "$SCRIPT_DIR/frontend/" "s3://$S3_BUCKET/frontend/" \
    --content-type "text/html" \
    --exclude "*" --include "*.html"

aws s3 sync "$SCRIPT_DIR/frontend/" "s3://$S3_BUCKET/frontend/" \
    --content-type "application/javascript" \
    --exclude "*" --include "*.js"

aws s3 sync "$SCRIPT_DIR/frontend/" "s3://$S3_BUCKET/frontend/" \
    --content-type "image/x-icon" \
    --exclude "*" --include "*.ico"

# Upload the logo
if [ -f "$SCRIPT_DIR/logo.jpg" ]; then
    aws s3 cp "$SCRIPT_DIR/logo.jpg" "s3://$S3_BUCKET/frontend/logo.jpg" --content-type "image/jpeg"
fi

echo ""
echo "=== Deployment Complete ==="
echo ""
echo "Frontend URL: ${WEBSITE_URL}/frontend/index.html"
echo "API URL:      $API_URL"
echo ""
echo "Users can now navigate to the frontend URL to upload and process images."
